import Header from '../../Components/Rasindu/Header';
import '../../Components/Rasindu/css/report.css';
import 'jspdf-autotable';
import jsPDF from 'jspdf';
import Axios from 'axios';
import React, { useState, useEffect } from "react";

function FinalReport() {
  const [totalIncome, setTotalIncome] = useState(0);
  const [totalExpenses, setTotalExpenses] = useState(0);
  const [profit, setProfit] = useState(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const bankIncomeResponse = await Axios.get('http://localhost:8070/api/bpayment');
        const creditIncomeResponse = await Axios.get('http://localhost:8070/api/cards');
        const directIncomeResponse = await Axios.get('http://localhost:8070/api/dpayment');
        const expenseResponse = await Axios.get('http://localhost:8070/expence');

        const bankIncome = bankIncomeResponse.data || [];
        const creditIncome = creditIncomeResponse.data || [];
        const directIncome = directIncomeResponse.data || [];
        const expenses = expenseResponse.data || [];

        const totalIncome = bankIncome.reduce((acc, income) => acc + income.amount, 0) +
          creditIncome.reduce((acc, income) => acc + income.amount, 0) +
          directIncome.reduce((acc, income) => acc + income.amount, 0);
        
        const totalExp = expenses.reduce((acc, exp) => acc + exp.amount, 0);

        setTotalIncome(totalIncome);
        setTotalExpenses(totalExp);
        setProfit(totalIncome - totalExp);
        setLoading(false);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, []);

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(10);
    doc.text("Protons E&E", 10, 10);
    doc.text("+94 774015896", 10, 20);
    doc.text("protons@gmail.com", 10, 30);
    doc.text("", 10, 40);
    doc.setLineWidth(0.1);
    doc.setDrawColor(0);
    doc.line(10, 45, 200, 45);
    doc.setFontSize(18);
    doc.text("Final Report", 10, 60);
    doc.setLineWidth(0.1);
    doc.line(10, 65, 200, 65);
    doc.text(`Total Income: Rs.${totalIncome}`, 10, 80);
    doc.text(`Total Expenses: Rs.${totalExpenses}`, 10, 90);
    doc.text(`Profit: Rs.${profit}`, 10, 100);
    doc.setFontSize(5);
    doc.text("Generated by Financial Manager", 150, 200);
    doc.save(`final-report.pdf`);
  };

  return (
    <div className="body1">
      <Header />
      <br />
      <br />
      <div>
        <button 
          style={{ color: "#ffffff", padding: "px 20px", fontSize: "20px", background: "rgb(236, 67, 0)", marginLeft: "20px", width: "200px", borderRadius: "10px" }}
          onClick={downloadPDF}
        >
          Download PDF
        </button>
        <br />
        <br />
      </div>
      <br />
      <br />
      <div className="container" id='report' style={{backgroundColor:" #fff"}}>
        <p className='rReportp'>Protons E&E</p>
        <p className='rReportp'>+94 774015896</p>
        <p className='rReportp'>protons@gmail.com</p>
        <h3 className='rh3Report'>Final Report</h3>
        <br />
        <br />
        <table className='rTabaleReport'>
          <thead>
            <tr className="rtrTable">
              <th className='rthReport'>Item</th>
              <th className='rthReport'>Amount (Rs.)</th>
            </tr>
          </thead>
          <tbody>
            <tr className="rtrTable">
              <td className='rtdReport'>Total Income</td>
              <td className='rtdReport'>{totalIncome}</td>
            </tr>
            <tr className="rtrTable">
              <td className='rtdReport'>Total Expenses</td>
              <td className='rtdReport'>{totalExpenses}</td>
            </tr>
            <tr className="rtrTable">
              <td className='rtdReport'>Profit</td>
              <td className='rtdReport'>{profit}</td>
            </tr>
          </tbody>
        </table>
        <br />
        <div className="rfooter">
          <p>Generated by Financial Manager</p>
        </div>
      </div>
      <br></br>
      <br></br>
    </div>
  );
}

export default FinalReport;
